In [32]:
import os 
import pandas as pd
import torch
import glob
import json
import natsort
import csv
import cv2
import urllib


In [3]:
# import torch, json, pandas

# # custom_Model_using source
model = torch.hub.load('ultralytics/yolov5', 'custom', path="/home/link-lap-24/Downloads/yolo_testng/PyK9F4OWSV9tJ6q.pt" , force_reload=True)

# # results = model("/content/drive/MyDrive/Dunk/dunk1_fr/182.jpg")
# # tags = json.loads(results.pandas().xyxy[0].to_json(orient="records"))

Downloading: "https://github.com/ultralytics/yolov5/archive/master.zip" to /home/link-lap-24/.cache/torch/hub/master.zip
YOLOv5 🚀 2023-1-27 Python-3.8.10 torch-1.8.1+cu111 CPU

Fusing layers... 
YOLOv5l summary: 367 layers, 46108278 parameters, 0 gradients, 107.6 GFLOPs
Adding AutoShape... 


In [27]:
import glob
import os
img_path="/home/link-lap-24/Downloads/yolo_testng/fr/"

final_path=natsort.natsorted(glob.glob(img_path + "*.jpg"))
# final_path=os.listdir('/content/drive/MyDrive/Dunk/dunk1_fr')
# print(final_path)
data={}

for ind,path in enumerate(final_path):
#     print(path)
    results = model(path)
    tags2 = json.loads(results.pandas().xyxy[0].to_json(orient="records"))
    basename=os.path.basename(path)
#     print(basename)
    if basename in data:
        data.append(tags2)
    else:
        data[basename]=tags2

  

In [97]:
# for key,value in data.items():
#     if value not in data.values():
#         data[key]=value


In [99]:
data

{'8.jpg': [{'xmin': 949.9279174805,
   'ymin': 1058.4741210938,
   'xmax': 996.4447631836,
   'ymax': 1080.0,
   'confidence': 0.8087053299,
   'class': 0,
   'name': 'blur_ball'}],
 '9.jpg': [{'xmin': 950.5204467773,
   'ymin': 1059.2137451172,
   'xmax': 996.6340942383,
   'ymax': 1080.0,
   'confidence': 0.8065103889,
   'class': 0,
   'name': 'blur_ball'}],
 '10.jpg': [{'xmin': 950.9623413086,
   'ymin': 1059.3724365234,
   'xmax': 996.6174926758,
   'ymax': 1080.0,
   'confidence': 0.8039242625,
   'class': 0,
   'name': 'blur_ball'}],
 '14.jpg': [{'xmin': 951.216796875,
   'ymin': 1059.5194091797,
   'xmax': 996.6344604492,
   'ymax': 1080.0,
   'confidence': 0.7958163023,
   'class': 0,
   'name': 'blur_ball'}],
 '15.jpg': [{'xmin': 951.2571411133,
   'ymin': 1059.5614013672,
   'xmax': 996.6286621094,
   'ymax': 1080.0,
   'confidence': 0.7950014472,
   'class': 0,
   'name': 'blur_ball'}],
 '16.jpg': [{'xmin': 951.5087280273,
   'ymin': 1059.7612304688,
   'xmax': 996.76324462

In [ ]:
result = {}

for key,value in input_raw.items():
    if value not in result.values():
        result[key] = value

print result

In [38]:
# for key,value in data.items():
#     print(key)
#     for i in value:
# #         print(i)
#         for j,k in i.items():
#             print(k)
        

1.jpg
951.5087280273
1059.7612304688
996.7632446289
1080.0
0.7968549728
0
blur_ball
2.jpg
951.5123901367
1059.7620849609
996.7608642578
1080.0
0.7968741059
0
blur_ball
3.jpg
951.5059814453
1059.7624511719
996.7645263672
1080.0
0.7967919707
0
blur_ball
4.jpg
950.8878173828
1058.4714355469
997.4735107422
1080.0
0.8234812021
0
blur_ball
5.jpg
950.876953125
1058.4678955078
997.4842529297
1080.0
0.8234047294
0
blur_ball
6.jpg
950.923828125
1058.6976318359
998.1436157227
1080.0
0.8126193285
0
blur_ball
1080.0989990234
134.634979248
1107.0911865234
164.1287536621
0.3696787059
0
blur_ball
7.jpg
900.471862793
578.873840332
932.4651489258
606.5084228516
0.814891696
0
blur_ball
950.130859375
1055.6802978516
999.9456176758
1080.0
0.7502589226
0
blur_ball
8.jpg
894.9404296875
585.612487793
929.9170532227
614.1065063477
0.7406551838
0
blur_ball
952.8957519531
1056.087890625
1000.3208007812
1080.0
0.678619206
0
blur_ball
499.3768005371
692.3931884766
522.1836547852
710.0675048828
0.2820715904
0
blur_

In [19]:
# image_path="/home/link-lap-24/Downloads/yolo_testng/fr/"
# com_path=natsort.natsorted(glob.glob(image_path + "*.jpg"))
# # print(com_path)
# for i_path in com_path:
# #     print(i_path)
#     frame = cv2.imread(i_path)
#     path=os.path.basename(i_path)
#     print(path)

#     for key,value in data.items():

# #         print(value)
#         for i in value:
            
# #             print(key)
# #             print(i)
            
#             xmin=int(i["xmin"])#
#             ymin=int(i["ymin"])

#             top_left=f"""{xmin},{ymin}"""
# #             print(top_left)
#             xmax=int(i["xmax"])
#             ymax=int(i["ymax"])
#             bottom_left=f"""{xmax},{ymax}"""
#     #         print(bottom_left)
#             confidence=i["confidence"]
#             x1,y1,x2,y2=xmin,ymin,xmax,ymax 
#             clas=i["class"]
#             color = (255, 0, 0)
#             thickness = 2
#             text="tennis"
#             cv2.rectangle(frame, (xmin, ymin),(xmax,ymax), color, thickness)
#             #image=cv2.putText(frame, text, (35, 50), cv2.FONT_HERSHEY_SIMPLEX,1.25, (0, 255, 0), 3)

# #             cv2.imshow(window_name, image)
#         cv2.imwrite(path + ".jpg",frame)
            
# #             cv2.imwrite(path + ".jpg",image)

        
# #     for xmin in value[]:
# #         for t in xmin.keys():
# #             print(t)
# # # print(data[0][7058])


6.jpg
7.jpg
8.jpg
9.jpg
10.jpg
16.jpg
17.jpg
18.jpg
19.jpg
20.jpg
26.jpg
27.jpg
28.jpg
29.jpg
30.jpg
36.jpg
37.jpg
38.jpg
39.jpg


In [96]:
image_path="/home/link-lap-24/Downloads/yolo_testng/fr/"
com_path=natsort.natsorted(glob.glob(image_path + "*.jpg"))
new_path='/home/link-lap-24/Downloads/yolo_testng/dete/'
# print(com_path)
for i_path in com_path:
#     print(i_path)
    frame = cv2.imread(i_path)
#     print(frame)
    path=os.path.basename(i_path)
#     print(path)


    result=data[path] 
    print(result)
#     print("*"*100)
    for i in result:
        x1, y1, x2, y2, score = i["xmin"], i["ymin"], i["xmax"], i["ymax"], round(i["confidence"]*100,2)
        x1, y1, x2, y2 = list(map(int, [x1, y1, x2, y2,]))
        text=f"""{score}"""
#         print(type(score))
        
    
        img=cv2.rectangle(frame, (x1, y1), (x2, y2), (255, 0, 0), 3)
        img=cv2.putText(frame, text, (35, 50), cv2.FONT_HERSHEY_SIMPLEX,1.25, (0, 255, 0), 3)
        print(img)
#     img=cv2.imwrite(new_path + path ,frame)



[{'xmin': 949.9279174805, 'ymin': 1058.4741210938, 'xmax': 996.4447631836, 'ymax': 1080.0, 'confidence': 0.8087053299, 'class': 0, 'name': 'blur_ball'}]
[[[ 38  23  31]
  [ 19   6  14]
  [ 11   0   8]
  ...
  [  1   4   2]
  [  9  12  10]
  [  3   6   4]]

 [[ 38  23  31]
  [ 19   6  14]
  [ 11   0   8]
  ...
  [  1   4   2]
  [  9  11  11]
  [  3   6   4]]

 [[ 38  23  31]
  [ 19   6  14]
  [ 11   0   8]
  ...
  [  1   3   3]
  [  9  11  12]
  [  3   5   5]]

 ...

 [[100 101  99]
  [ 90  91  89]
  [ 89  90  88]
  ...
  [ 87  82  83]
  [ 87  82  83]
  [ 87  82  83]]

 [[100 101  99]
  [ 90  91  89]
  [ 89  90  88]
  ...
  [ 87  82  83]
  [ 87  82  83]
  [ 87  82  83]]

 [[100 101  99]
  [ 90  91  89]
  [ 89  90  88]
  ...
  [ 88  83  84]
  [ 88  83  84]
  [ 88  83  84]]]
[{'xmin': 950.5204467773, 'ymin': 1059.2137451172, 'xmax': 996.6340942383, 'ymax': 1080.0, 'confidence': 0.8065103889, 'class': 0, 'name': 'blur_ball'}]
[[[ 18   3  11]
  [ 16   3  11]
  [ 14   3  11]
  ...
  [  1   4

[{'xmin': 952.96875, 'ymin': 1060.7873535156, 'xmax': 996.9807128906, 'ymax': 1080.0, 'confidence': 0.7881339192, 'class': 0, 'name': 'blur_ball'}, {'xmin': 926.0690917969, 'ymin': 499.4884643555, 'xmax': 956.0465698242, 'ymax': 548.9123535156, 'confidence': 0.6068477631, 'class': 0, 'name': 'blur_ball'}]
[[[ 10  25  28]
  [  6  18  22]
  [  4  10  15]
  ...
  [  2   0  15]
  [  9   6  22]
  [  4   1  17]]

 [[ 10  25  28]
  [  6  18  22]
  [  4  10  15]
  ...
  [  2   0  15]
  [ 10   7  23]
  [  4   1  17]]

 [[ 10  25  28]
  [  6  18  22]
  [  4  10  15]
  ...
  [  2   0  15]
  [ 10   7  23]
  [  4   1  17]]

 ...

 [[100 100 100]
  [ 87  88  86]
  [ 87  88  86]
  ...
  [ 84  82  82]
  [ 84  82  82]
  [ 84  82  82]]

 [[100 100 100]
  [ 87  88  86]
  [ 87  88  86]
  ...
  [ 84  82  82]
  [ 84  82  82]
  [ 84  82  82]]

 [[100 100 100]
  [ 87  88  86]
  [ 87  88  86]
  ...
  [ 84  82  82]
  [ 84  82  82]
  [ 84  82  82]]]
[[[ 10  25  28]
  [  6  18  22]
  [  4  10  15]
  ...
  [  2   

In [37]:
# for i in data:
#     print(i)

8.jpg
9.jpg
10.jpg
14.jpg
15.jpg
16.jpg
24.jpg
25.jpg
26.jpg
27.jpg
28.jpg
29.jpg
37.jpg
38.jpg
39.jpg
40.jpg
44.jpg
45.jpg
49.jpg
50.jpg
54.jpg
55.jpg
56.jpg


In [ ]:
# Python program to explain cv2.rectangle() method

# importing cv2
import cv2

# path
path = r'C:\Users\Rajnish\Desktop\geeksforgeeks\geeks.png'

# Reading an image in default mode
image = cv2.imread(path)

# Window name in which image is displayed
window_name = 'Image'

# Start coordinate, here (5, 5)
# represents the top left corner of rectangle
start_point = (5, 5)

# Ending coordinate, here (220, 220)
# represents the bottom right corner of rectangle
end_point = (220, 220)

# Blue color in BGR
color = (255, 0, 0)

# Line thickness of 2 px
thickness = 2

# Using cv2.rectangle() method
# Draw a rectangle with blue line borders of thickness of 2 px
image = cv2.rectangle(image, start_point, end_point, color, thickness)

# Displaying the image
cv2.imshow(window_name, image)


In [39]:
# df = pd.DataFrame.from_dict(data) 

# df.to_csv (r'gen.csv', index = False, header=True)


In [ ]:
import cv2

predictions = {'predictions': [{'x': 1012.0, 'y': 593.5, 'width': 406.0, 'height': 443.0, 'confidence': 0.7369905710220337, 'class': 'Paper', 'image_path': 'example.jpg', 'prediction_type': 'ObjectDetectionModel'}], 'image': {'width': 1436, 'height': 956}}

for bounding_box in predictions["predictions"]:
    x0 = bounding_box['x'] - bounding_box['width'] / 2
    x1 = bounding_box['x'] + bounding_box['width'] / 2
    y0 = bounding_box['y'] - bounding_box['height'] / 2
    y1 = bounding_box['y'] + bounding_box['height'] / 2
    
    start_point = (int(x0), int(y0))
    end_point = (int(x1), int(y1))
    cv2.rectangle(img, start_point, end_point, color=(0,255,0), thickness=2)
   
cv2.imwrite("example_with_bounding_boxes.jpg", image)

In [18]:
import os
import shutil
import glob
import cv2
import requests
from termcolor import colored
import json
import os
# video_path = r""
# Frames = r"/home/multi-sy-007/Desktop/work/Basket_Ball/Frames"

DETECTION_URL = "http://localhost:5000/v1/object-detection/yolov5s"

# def files_in_folder(folder_path):
#     all_files = sorted(glob.glob(video_path + '/' + '*.png'))
#     #print(all_files)
#     for file in all_files:
#         shutil.move(file,Frames)

# files_in_folder(video_path)

#GET detection on images. Generate json response
def get_detections(IMAGE):
    with open(IMAGE, "rb") as f:
        image_data = f.read()
    response = requests.post(DETECTION_URL, files={"image": image_data}).json()
    return response

# Get results inj terms of co-ordinates
def get_cords_only(result):
    return [list(map(float,[i['xmin'], i['ymin'], i['xmax'], i['ymax'],(i['confidence'])])) for i in result]

# Draw Label & rectangle on image and save that image to new detection folder
def draw_box(image, result1, output_key,label):
    img_read = cv2.imread(image)
    Detection = Main_folder + "/df/"

    for res_i in result1:
        #print(type(res_i))

        x1, y1, x2, y2 = res_i['xmin'], res_i['ymin'], res_i['xmax'], res_i['ymax']
        #print(x1, y1, x2, y2)
        score=res_i['confidence']*100
        x1, y1, x2, y2 = list(map(int, [x1, y1, x2, y2]))
        # print(f'X1 {x1} : Y1 {y1} : X2 {x2} : Y2 {y2}')
        img_read = cv2.rectangle(img_read, (x1, y1), (x2, y2), (255, 0, 0), 2)
        img_read = cv2.putText(img_read, f"{score}", (x1, y1), cv2.FONT_HERSHEY_SIMPLEX, 2, 255)
    #print(Detection+output_key)
    tempT = cv2.imwrite(Detection+output_key, img_read)
    del tempT

def get_detection_on_frames(Main_folder):
    frame_folder = Main_folder + "/fr/"
    Detection = Main_folder + "/df/"

    all_detections = {}
    all_images = sorted(glob.glob(frame_folder + '*.png'), key=lambda x: int(x.split("/")[-1].split(".")[0]))
    #print(colored((all_images,blue))
    for index, image in enumerate(all_images):

        result1 = get_detections(image)
        print(result1)
        #print(colored(result1, "yellow"))
        #result1=[d for d in result1 if d.get('name') == "ball"]
        #result1 = [d for d in result1 if d.get('confidence') >=0.30]

        #print(colored(result1,"red"))

        '''
         0{'xmin': 566.3480224609, 'ymin': 562.5621337891, 'xmax': 594.3916015625, 'ymax': 587.9360351562,
          'confidence': 0.7584906816, 'class': 0, 'name': 'ball'}]
        '''
        if len(result1)==0:
            shutil.copy(image, Detection)
        else:
            out_key = os.path.basename(image)
            for result in result1:
                k=result["confidence"]
                label=result["class"]
                #print(label)
                #if label==0:
                    #if k >= 0.30 :
                    #result = sorted(result, key=operator.itemgetter("confidence"), reverse=True)
                    #result = [result[0]]

            draw_box(image, result1, out_key,label)
            all_detections[image.split("/")[-1]] = result1
             #print(all_detections)
    return all_detections

Main_folder= r"/home/link-lap-24/Downloads/yolo_testng"
frame_folder = Main_folder + "/fr/"
#print(frame_folder)
all_d = get_detection_on_frames(Main_folder)
json.dump(all_d, open(f"{Main_folder + '/Results/' + 'all_det_1.json'}", 'w'))

In [1]:
dictt={"players":[{"scores":[122,455,545,54]}]}
tdd=dictt["players"]
print(tdd)
# tdd["scores"]

[{'scores': [122, 455, 545, 54]}]


In [4]:
for key,value in dictt.items():
    print(value)
    for k in value:
        print(k)
        for t,y in k.items():
            print(y)

[{'scores': [122, 455, 545, 54]}]
{'scores': [122, 455, 545, 54]}
[122, 455, 545, 54]


In [33]:
df={'_id': '63dcd591671e5d8467abddce', 'annotations': {'line': [], 'point': [], 'rect': [261, 276, 58, 72, 'stump'], 'circle': [], 'rectWithCircle': []}, 'imageUrl': 'https://ai-studio-new.s3-ap-south-1.amazonaws.com/ai-studio/63dcc8ff671e5d8467abdcbc/data/68a740-0b03-51ac-0280-45af5443capng.png'}
df


{'_id': '63dcd591671e5d8467abddce',
 'annotations': {'line': [],
  'point': [],
  'rect': [261, 276, 58, 72, 'stump'],
  'circle': [],
  'rectWithCircle': []},
 'imageUrl': 'https://ai-studio-new.s3-ap-south-1.amazonaws.com/ai-studio/63dcc8ff671e5d8467abdcbc/data/68a740-0b03-51ac-0280-45af5443capng.png'}

In [90]:
# final={}
tu=df['annotations']['rect']
x1=tu[0]
y1=tu[1]
x2=tu[2]
y2=tu[3]


In [92]:
x2

58

In [76]:
rect=tu["rect"][0:4]

x1_y1=str(rect[0:2])
tp=x1_y1.replace(",",":")
print(tp)

x2_y2=str(rect[2:4])
tt=x2_y2.replace(",",":")
tt


# left=tu["rect"][0]
# right=tu['rect'][1]
# top=tu['rect'][2]
# bottom=tu['rect'][3]

[261: 276]


'[58: 72]'

In [36]:
url=df["imageUrl"]
url

'https://ai-studio-new.s3-ap-south-1.amazonaws.com/ai-studio/63dcc8ff671e5d8467abdcbc/data/68a740-0b03-51ac-0280-45af5443capng.png'

In [37]:
final[url]=rect
final


{'https://ai-studio-new.s3-ap-south-1.amazonaws.com/ai-studio/63dcc8ff671e5d8467abdcbc/data/68a740-0b03-51ac-0280-45af5443capng.png': [261,
  276,
  58,
  72]}

In [46]:
os.getcwd()

'/home/link-lap-24/Downloads/yolo_testng'

In [47]:
image=urllib.request.urlretrieve(url,"kf")

('kf', <http.client.HTTPMessage at 0x7f1ff1954280>)

In [88]:
import cv2
import numpy as np

im_path="/home/link-lap-24/Downloads/yolo_testng/kf"
img = cv2.imread(im_path)
print(img.shape) # Print image shape
# cv2.imshow("original", img)
 
# Cropping an image
cropped_image = img[x1,x2,y1,y2]
 
# Display cropped image
# cv2.imshow("cropped", cropped_image)
 
# Save the cropped image
cv2.imwrite("Cropped Image.jpg", cropped_image)
 

[ WARN:0@8817.149] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/home/link-lap-24/Downloads/yolo_testng/kf'): can't open/read file: check file path/integrity


AttributeError: 'NoneType' object has no attribute 'shape'

In [ ]:
for key,value in data.items():
    for k in value:
        for t,y in k.items():

In [62]:
from PIL import Image


im = Image.open(im_path).convert('L')
im = im.crop((f"""{left},{right},{top},{bottom}"""))
im.save('_0.png')

ValueError: Coordinate 'right' is less than 'left'